stages:
  - test
  - build

variables:
  BUILD_OUTPUT: out

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

test:
  stage: test
  image: docker.io/library/golang:alpine@sha256:ac09a5f469f307e5da71e766b0bd59c9c49ea460a528cc3e6686513d64a6f1fb
  script:
    - go test
  extends: .go-cache

build:
  stage: build
  image: docker.io/library/golang:alpine@sha256:ac09a5f469f307e5da71e766b0bd59c9c49ea460a528cc3e6686513d64a6f1fb
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never
  before_script: 
    - mkdir -pv $BUILD_OUTPUT
  script:
    - go build -o $BUILD_OUTPUT
  extends: .go-cache
  artifacts:
    when: on_success
    expire_in: "1 hour"
    paths:
      - $BUILD_OUTPUT