stages:
  - test
  - build

variables:
  BUILD_OUTPUT: out

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

test:
  stage: test
  image: docker.io/library/golang:alpine
  script:
    - go test
  extends: .go-cache

build:
  stage: build
  image: docker.io/library/golang:alpine
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never
  before_script: 
    - mkdir -pv $BUILD_OUTPUT
  script:
    - go build -o $BUILD_OUTPUT
  extends: .go-cache
  artifacts:
    when: on_success
    expire_in: "1 hour"
    paths:
      - $BUILD_OUTPUT